import React, { useEffect, useState } from 'react';
import { request } from '../../api/client';

const label = (item) => item.status === 'published' ? '团队已发布' : item.status === 'withdrawn' ? '已撤回为私有' : '私有草稿';

function Confirmation({ target, onCancel, onConfirm, busy }) {
  if (!target) return null;
  const publish = target.action === 'publish';
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="确认方案状态"><p className="eyebrow">需要人工确认</p><h3>{publish ? '发布到团队？' : '撤回为私有？'}</h3><p className="muted">{publish ? '发布后团队成员可以查看此方案。' : '撤回后团队成员不能继续查看此方案。'}</p><div className="modal-actions"><button type="button" className="ghost" onClick={onCancel}>取消</button><button type="button" className={publish ? 'publish' : 'danger'} onClick={onConfirm} disabled={busy}>确认{publish ? '发布' : '撤回'}</button></div></section></div>;
}

export function SolutionsPage({ initialItems = [] }) {
  const [items, setItems] = useState(initialItems); const [editor, setEditor] = useState(null); const [notice, setNotice] = useState({ text: '', error: false }); const [pending, setPending] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { setItems((await request('/api/content/solutions')).solutions || []); } catch (error) { setNotice({ text: error.message, error: true }); } };
  useEffect(() => { load(); }, []);
  async function open(item) { try { const body = await request(`/api/content/solutions/${encodeURIComponent(item.id)}`); setEditor({ ...body.solution, isNew: false }); } catch (error) { setNotice({ text: error.message, error: true }); } }
  async function save(event) { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); try { const payload = { title: f.get('title'), description: f.get('description'), solutionMarkdown: f.get('solutionMarkdown') }; const body = editor?.isNew ? await request('/api/content/solutions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }) : await request(`/api/content/solutions/${encodeURIComponent(editor.id)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); setEditor(null); setNotice({ text: `方案已保存为${label(body.solution)}。`, error: false }); await load(); } catch (error) { setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  async function transition() { if (!pending) return; setBusy(true); try { await request(`/api/content/solutions/${encodeURIComponent(pending.id)}/${pending.action}`, { method: 'POST' }); setPending(null); setNotice({ text: pending.action === 'publish' ? '方案已发布到团队。' : '方案已撤回为私有草稿。', error: false }); setEditor(null); await load(); } catch (error) { setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  async function toKnowledge(event) { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); try { await request(`/api/content/solutions/${encodeURIComponent(editor.id)}/to-knowledge`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ title: f.get('title'), category: f.get('category'), tags: String(f.get('tags') || '').split(',').map((tag) => tag.trim()).filter(Boolean), markdown: f.get('markdown') }) }); setNotice({ text: '已创建私有知识草稿，可在知识库继续编辑。', error: false }); setEditor(null); } catch (error) { setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  if (editor) return <section className="panel editor-panel"><div className="section-head"><div><p className="eyebrow">{editor.isNew ? '新建私有方案' : label(editor)}</p><h3>{editor.isNew ? '撰写方案' : editor.title}</h3></div><button className="ghost" onClick={() => setEditor(null)}>返回列表</button></div><form className="stack" onSubmit={save}><label>方案标题<input name="title" defaultValue={editor.title} required /></label><label>问题背景与约束<textarea name="description" defaultValue={editor.description || ''} /></label><label>方案正文<textarea className="knowledge-content" name="solutionMarkdown" defaultValue={editor.solutionMarkdown || ''} required /></label><div className="form-actions"><span className="muted">保存为私有草稿，发布须单独确认</span><button disabled={busy}>{busy ? '保存中…' : '保存私有草稿'}</button></div></form>{!editor.isNew && <><div className="form-actions content-actions"><button type="button" className={editor.status === 'published' ? 'ghost danger' : 'publish'} onClick={() => setPending({ id: editor.id, action: editor.status === 'published' ? 'withdraw' : 'publish' })}>{editor.status === 'published' ? '撤回团队' : '发布到团队'}</button></div>{editor.references?.length > 0 && <div className="source-card"><p className="eyebrow">来源追溯</p>{editor.references.map((reference, index) => <p key={`${reference.sourceType}-${reference.sourceId || index}`} className="muted">{reference.sourceType === 'conversation' ? `来自对话 · 完成 ${reference.completedTurnCount || 0} 轮` : `来源：${reference.sourceType} · ${reference.sourceId}`}{reference.private ? ' · 私有来源已隐藏' : ''}</p>)}</div>}<form className="stack source-convert" onSubmit={toKnowledge}><p className="eyebrow">继续沉淀</p><h4>转为知识草稿</h4><label>知识标题<input name="title" defaultValue={editor.title} required /></label><label>分类<input name="category" placeholder="例如 runtime" /></label><label>标签<input name="tags" placeholder="用逗号分隔" /></label><label>知识正文<textarea name="markdown" defaultValue={editor.solutionMarkdown || ''} required /></label><button disabled={busy}>{busy ? '创建中…' : '创建私有知识草稿'}</button></form></>}<Confirmation target={pending} onCancel={() => setPending(null)} onConfirm={transition} busy={busy} /></section>;
  return <section className="panel"><div className="section-head"><div><h3>我的需求方案</h3><p className="muted">方案默认私有，人工发布后才供团队复用。</p></div><button onClick={() => setEditor({ title: '', description: '', solutionMarkdown: '', isNew: true })}>新建方案</button></div><p className={notice.error ? 'notice error' : 'notice success'} role="status">{notice.text}</p><div className="list">{items.length ? items.map((item) => <article className="content-card" key={item.id}><button className="knowledge-item" onClick={() => open(item)}><b>{item.title}</b><span>{label(item)} · v{item.version}</span></button><button type="button" className={item.status === 'published' ? 'ghost danger' : 'publish'} onClick={() => setPending({ id: item.id, action: item.status === 'published' ? 'withdraw' : 'publish' })} disabled={busy}>{item.status === 'published' ? '撤回团队' : '发布到团队'}</button></article>) : <div className="empty">暂无版本化需求方案</div>}</div><Confirmation target={pending} onCancel={() => setPending(null)} onConfirm={transition} busy={busy} /></section>;
}
