'use strict';
const ERROR_CODES = Object.freeze({
  SESSION_INVALID: 'SESSION_INVALID',
  CSRF_INVALID: 'CSRF_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  REQUEST_FAILED: 'REQUEST_FAILED',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ARCHIVED: 'CONVERSATION_ARCHIVED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  USER_QUEUE_LIMIT: 'USER_QUEUE_LIMIT',
  GATEWAY_UNAVAILABLE: 'GATEWAY_UNAVAILABLE'
});
module.exports = { ERROR_CODES };
