'use strict';
const ERROR_CODES = Object.freeze({ SESSION_INVALID:'SESSION_INVALID', CSRF_INVALID:'CSRF_INVALID', FORBIDDEN:'FORBIDDEN', REQUEST_FAILED:'REQUEST_FAILED' });
module.exports = { ERROR_CODES };
