import React, { useEffect, useMemo, useState } from 'react';
import { request } from '../../api/client';

const label = (item) => item.status === 'published' ? '团队已发布' : item.status === 'withdrawn' ? '已撤回为私有' : '私有草稿';

function Confirmation({ target, onCancel, onConfirm, busy }) {
  if (!target) return null;
  const publish = target.action === 'publish';
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="确认内容状态"><p className="eyebrow">需要人工确认</p><h3>{publish ? '发布到团队？' : '撤回为私有？'}</h3><p className="muted">{publish ? '发布后团队成员可以搜索和查看此版本。' : '撤回后团队成员将不能继续访问此内容。'}</p><div className="modal-actions"><button className="ghost" type="button" onClick={onCancel}>取消</button><button className={publish ? 'publish' : 'danger'} type="button" onClick={onConfirm} disabled={busy}>确认{publish ? '发布' : '撤回'}</button></div></section></div>;
}

export function KnowledgePage({ initialEditor = null, initialItems = [] }) {
  const [items, setItems] = useState(initialItems); const [query, setQuery] = useState(''); const [editor, setEditor] = useState(initialEditor); const [notice, setNotice] = useState({ text: '', error: false }); const [pending, setPending] = useState(null); const [preview, setPreview] = useState(null); const [diff, setDiff] = useState(null); const [busy, setBusy] = useState(false);
  const load = async () => { try { setItems((await request('/api/content/knowledge')).knowledge || []); } catch (error) { setNotice({ text: error.message, error: true }); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const value = query.trim(); if (!value) return undefined; let active = true; const timer = window.setTimeout(async () => { try { const body = await request(`/api/content/knowledge/search?q=${encodeURIComponent(value)}`); if (active) setItems(body.knowledge || []); } catch (error) { if (active) setNotice({ text: error.message, error: true }); } }, 250); return () => { active = false; window.clearTimeout(timer); }; }, [query]);
  const visible = useMemo(() => items, [items]);
  async function open(item) { try { const body = await request(`/api/content/knowledge/${encodeURIComponent(item.id)}`); setEditor({ ...body.knowledge, isNew: false, content: body.knowledge.markdown }); setPreview(null); setDiff(null); } catch (error) { setNotice({ text: error.message, error: true }); } }
  async function loadDiff(from, to) { if (!editor?.id) return; setBusy(true); try { setDiff(await request(`/api/content/knowledge/${encodeURIComponent(editor.id)}/diff?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`)); } catch (error) { setDiff(null); setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  async function save(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { const payload = { title: form.get('title'), category: form.get('category'), tags: String(form.get('tags') || '').split(',').map((value) => value.trim()).filter(Boolean), markdown: form.get('content') }; const body = editor?.isNew ? await request('/api/content/knowledge', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }) : await request(`/api/content/knowledge/${encodeURIComponent(editor.id)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); setEditor(null); setNotice({ text: `文档已保存为${label(body.knowledge)}。`, error: false }); await load(); } catch (error) { setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  async function transition() { if (!pending) return; setBusy(true); try { const body = await request(`/api/content/knowledge/${encodeURIComponent(pending.id)}/${pending.action}`, { method: 'POST' }); setPending(null); setNotice({ text: pending.action === 'publish' ? '已发布到团队。' : '已撤回为私有草稿。', error: false }); await load(); if (editor?.id === body.knowledge.id) setEditor({ ...editor, ...body.knowledge }); } catch (error) { setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  async function uploadAttachments(event) { const input = event.currentTarget; const files = [...input.files]; if (!files.length || !editor?.id) return; setBusy(true); try { for (const file of files) { const form = new FormData(); form.append('file', file); await request(`/api/content/knowledge/${encodeURIComponent(editor.id)}/attachments`, { method: 'POST', body: form }); } const body = await request(`/api/content/knowledge/${encodeURIComponent(editor.id)}`); setEditor({ ...body.knowledge, isNew: false, content: body.knowledge.markdown }); setNotice({ text: `已上传 ${files.length} 个附件，保存后仍仅本人可见。`, error: false }); } catch (error) { setNotice({ text: error.message, error: true }); } finally { input.value = ''; setBusy(false); } }
  async function previewAttachment(attachment) { if (!editor?.id) return; setBusy(true); try { const body = await request(`/api/content/knowledge/${encodeURIComponent(editor.id)}/attachments/${encodeURIComponent(attachment.id)}/preview`); setPreview({ name: attachment.originalName, ...body }); } catch (error) { setPreview(null); setNotice({ text: error.message, error: true }); } finally { setBusy(false); } }
  if (editor) return <section className="panel editor-panel">
    <div className="section-head"><div><p className="eyebrow">{editor.isNew ? '新建私有文档' : label(editor)}</p><h3>{editor.isNew ? '撰写 Markdown 文档' : editor.title}</h3></div><button className="ghost" onClick={() => setEditor(null)}>返回列表</button></div>
    <form className="stack" onSubmit={save}><label>标题<input name="title" defaultValue={editor.title} readOnly={!editor.isNew && !editor.id} required /></label><label>分类<input name="category" defaultValue={editor.category || ''} placeholder="如：GPU 选型" /></label><label>标签（逗号分隔）<input name="tags" defaultValue={(editor.tags || []).join(', ')} placeholder="如：H800, 容量" /></label><label>正文<textarea className="knowledge-content" name="content" defaultValue={editor.content || ''} placeholder="使用 Markdown 编写正文" required /></label><div className="form-actions"><span className="muted">保存后默认仅本人可见；发布必须单独确认</span><button disabled={busy}>{busy ? '保存中…' : '保存私有草稿'}</button></div></form>
    {!editor.isNew && <>
      <div className="row-actions content-actions"><label className="button ghost file-button">添加附件<input type="file" multiple accept=".md,.txt,.docx,.pdf,.json,.csv" onChange={uploadAttachments} disabled={busy} /></label><a className="button ghost" href={`/api/content/knowledge/${encodeURIComponent(editor.id)}/export`} download>导出知识包</a></div>
      {editor.attachments?.length > 0 && <div className="source-card"><p className="eyebrow">附件</p>{editor.attachments.map((attachment) => <div className="attachment-row" key={attachment.id}><span className="muted">{attachment.originalName} · {attachment.sizeBytes} bytes · SHA-256 {attachment.contentSha256.slice(0, 12)}…</span><button className="ghost" type="button" onClick={() => previewAttachment(attachment)} disabled={busy}>预览</button></div>)}</div>}
      {preview && <div className="attachment-preview"><div className="section-head"><p className="eyebrow">{preview.name} · {preview.format}</p><button className="ghost" type="button" onClick={() => setPreview(null)}>关闭</button></div><pre>{preview.text}{preview.truncated ? '\n…（预览已截断）' : ''}</pre></div>}
      {editor.versionHistory?.length > 1 && <div className="source-card version-history"><p className="eyebrow">版本历史</p>{editor.versionHistory.filter((version) => version.version < editor.version).map((version) => <button className="ghost" type="button" key={version.id} onClick={() => loadDiff(version.version, editor.version)} disabled={busy}>对比 v{version.version} → 当前 v{editor.version}</button>)}</div>}
      {diff && <div className="attachment-preview"><div className="section-head"><p className="eyebrow">v{diff.from.version} → v{diff.to.version} · {diff.diff.summary.additions} 增 / {diff.diff.summary.removals} 删</p><button className="ghost" type="button" onClick={() => setDiff(null)}>关闭</button></div><pre>{diff.diff.hunks.flatMap((hunk) => hunk.lines.map((line) => `${hunk.type === 'add' ? '+' : hunk.type === 'remove' ? '-' : ' '} ${line}`)).join('\n')}</pre></div>}
      <div className="form-actions content-actions"><button className={editor.status === 'published' ? 'ghost danger' : 'publish'} type="button" onClick={() => setPending({ id: editor.id, action: editor.status === 'published' ? 'withdraw' : 'publish' })} disabled={busy}>{editor.status === 'published' ? '撤回团队' : '发布到团队'}</button></div>
    </>}
    <Confirmation target={pending} onCancel={() => setPending(null)} onConfirm={transition} busy={busy} />
  </section>;
  return <section className="panel"><div className="section-head knowledge-head"><div><h3>知识库</h3><p className="muted">新内容默认私有；只有人工发布后才成为团队知识。</p></div><div className="row-actions"><button className="ghost" type="button" disabled>上传文件</button><button onClick={() => setEditor({ title: '', category: '', tags: [], content: '', isNew: true })}>新建文档</button></div></div><div className="knowledge-toolbar"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索标题或正文" aria-label="搜索知识库" /><span className="muted">{visible.length} 篇文档</span></div><p className={notice.error ? 'notice error' : 'notice success'} role="status">{notice.text}</p><div className="list knowledge-list">{visible.length ? visible.map((item) => <article className="content-card" key={item.id}><button className="knowledge-item" onClick={() => open(item)}><b>{item.title}</b><span>{item.preview || item.category || 'Markdown 文档'}</span><small>{label(item)} · v{item.version}</small></button><button type="button" className={item.status === 'published' ? 'ghost danger' : 'publish'} onClick={() => setPending({ id: item.id, action: item.status === 'published' ? 'withdraw' : 'publish' })} disabled={busy}>{item.status === 'published' ? '撤回团队' : '发布到团队'}</button></article>) : <div className="empty">{query ? '没有匹配的知识文档' : '暂无版本化知识文档'}</div>}</div><Confirmation target={pending} onCancel={() => setPending(null)} onConfirm={transition} busy={busy} /></section>;
}
